# Reto 3

## Miguel Ortiz y Andrea Castiella


In [10]:
import numpy  as np
import pandas as pd
import OurUtils as our
from sklearn.preprocessing import MinMaxScaler

In [11]:
# Read data
X_full = pd.read_csv('Reto 3-Dataset/reto3_trainX.csv', header=0, low_memory=False)
Y_full = pd.read_csv('Reto 3-Dataset/reto3_trainY.csv', header=0, low_memory=False)

print(X_full.head())
print(Y_full.head())

   altitud  azimut  inclinacion  DH_agua  DV_agua  DH_camino  sombra_9am  \
0     3351     354           19      450       95       1064         185   
1     2995      84            7      481       30       5154         231   
2     2884      72           25      210      -45        466         239   
3     3139      76           11      301       58       1368         234   
4     3018     312           17       30       10       1719         172   

   sombra_12pm  sombra_3pm  DH_fuego  ...  t31  t32  t33  t34  t35  t36  t37  \
0          203         153       711  ...    0    0    0    0    0    0    0   
1          227         129      5488  ...    0    0    0    0    0    0    0   
2          183          60      2123  ...    0    0    0    0    0    0    0   
3          220         117      3282  ...    0    0    1    0    0    0    0   
4          225         193      1961  ...    0    0    0    0    0    0    0   

   t38  t39  t40  
0    0    1    0  
1    0    0    0  
2    

## Split dataset
Train split: 80%

Validation split: 20%

In [12]:
# Split into train and validation
valid_size = 0.2
seed = 1234
X_train, Y_train, X_valid, Y_valid = \
   our.single_stratified_split(X_full, Y_full, test_size=valid_size, random_state=seed)

# from imblearn.over_sampling import SMOTE
# sm = SMOTE(random_state=seed)

# X_train, Y_train = sm.fit_resample(X_train, Y_train)
from sklearn.utils import resample

x_oversampled, y_oversampled = resample(X_train[Y_train.values == 1],
                                        Y_train[Y_train.values == 1],
                                        replace=True,
                                        n_samples=X_train[Y_train.values == 3].shape[0],
                                        random_state=123)
print(x_oversampled.shape)
X_balanced = np.vstack((X_train[Y_train.values == 3], x_oversampled))
y_balanced = np.hstack((Y_train[Y_train.values == 3], y_oversampled))
print(X_balanced.shape)

x_overversampled, y_oversampled = resample(X_train[Y_train.values == 2],
                                        Y_train[Y_train.values == 2],
                                        replace=True,
                                        n_samples=X_train[Y_train.values == 3].shape[0],
                                        random_state=123)
X_balanced = np.vstack((X_balanced, x_oversampled))
y_balanced = np.hstack((y_balanced, y_oversampled))
print(X_balanced.shape)

x_oversampled, y_oversampled = resample(X_train[Y_train.values == 4],
                                        Y_train[Y_train.values == 4],
                                        replace=True,
                                        n_samples=X_train[Y_train.values == 3].shape[0],
                                        random_state=123)
X_balanced = np.vstack((X_balanced, x_oversampled))
y_balanced = np.hstack((y_balanced, y_oversampled))
print(X_balanced.shape)

x_oversampled, y_oversampled = resample(X_train[Y_train.values == 5],
                                        Y_train[Y_train.values == 5],
                                        replace=True,
                                        n_samples=X_train[Y_train.values == 3].shape[0],
                                        random_state=123)
X_balanced = np.vstack((X_balanced, x_oversampled))
y_balanced = np.hstack((y_balanced, y_oversampled))
print(X_balanced.shape)

x_oversampled, y_oversampled = resample(X_train[Y_train.values == 6],
                                        Y_train[Y_train.values == 6],
                                        replace=True,
                                        n_samples=X_train[Y_train.values == 3].shape[0],
                                        random_state=123)
X_balanced = np.vstack((X_balanced, x_oversampled))
y_balanced = np.hstack((y_balanced, y_oversampled))
print(X_balanced.shape)

x_oversampled, y_oversampled = resample(X_train[Y_train.values == 7],
                                        Y_train[Y_train.values == 7],
                                        replace=True,
                                        n_samples=X_train[Y_train.values == 3].shape[0],
                                        random_state=123)
X_balanced = np.vstack((X_balanced, x_oversampled))
y_balanced = np.hstack((y_balanced, y_oversampled))
X_train = X_balanced
Y_train = y_balanced
print(X_balanced.shape)

(33894, 54)


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5721 and the array at index 1 has size 33894

## Feature selection

In [ ]:
scaler = MinMaxScaler()
X = scaler.fit_transform(X_train)
Y = Y_train.ravel() # Returns data as numpy array
# Y = Y_train.values.ravel()

##PCA

In [ ]:
print(X.shape)
print(Y, Y.shape)

(92961, 54)
[1 2 1 ... 3 2 2] (92961,)


In [ ]:
X_proy, pca = our.our_PCA(X)
num_of_pc = len(pca.singular_values_)
strTitle = '\n First %d principal components' %(num_of_pc)
print(strTitle)
print(pca.components_.T)
strTitle = '\n First %d singular values ' %(num_of_pc)
print(strTitle)
print(pca.singular_values_.T)
strTitle = '\n Explained Variance Ratio'
print(strTitle)
print(pca.explained_variance_ratio_.T)
strTitle = '\n Accumulated Explained Variance Ratio'
print(strTitle)
print(np.cumsum(pca.explained_variance_ratio_.T))

(40047, 11)

 First 11 principal components
[[-2.58818387e-01  1.32045670e-01  6.24635261e-02 -6.58025856e-02
   2.88295500e-01 -1.43430231e-01 -3.00071010e-02  2.69064357e-03
  -6.57455484e-02  4.37239430e-02  6.06521527e-02]
 [ 2.10040244e-03 -1.10792505e-01  6.54663340e-01 -4.04719596e-01
  -1.70571021e-01 -1.02619300e-01  3.71639056e-01  8.75528765e-02
  -1.45442205e-02 -6.63882746e-02 -3.88592109e-02]
 [ 8.81236388e-02 -3.98115060e-02 -4.12355890e-02  1.54572046e-01
  -2.77868417e-02 -1.43704435e-01  3.44731402e-01  5.18580681e-02
  -1.01809515e-01  5.97125236e-02  3.72672902e-02]
 [-7.40199314e-02 -6.76627067e-03  1.54235388e-02 -3.63523727e-02
   1.56428804e-01 -2.54549982e-01  1.08941157e-03 -6.34674385e-02
  -7.08756250e-02 -1.53029228e-02 -3.59405233e-02]
 [-2.33215953e-03 -2.23155738e-02 -6.99066470e-03 -1.10340314e-03
   7.42811116e-02 -1.74877141e-01  8.52330773e-02 -2.06550605e-02
  -8.15744610e-02 -1.74990969e-02 -7.16510778e-03]
 [-1.49542281e-01  1.24604355e-01  1.0170

## Multiclass. OvO vs OvR

In [ ]:
# Multiclass
from sklearn.multiclass import OneVsOneClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

max_depth = 10
base_clf = DecisionTreeClassifier(max_depth = max_depth, random_state=seed)

# base_clf = SVC(kernel='rbf', degree=2, gamma=1, random_state = seed)
X = X_proy
# Train OvO 
OvO_clf = OneVsOneClassifier(base_clf)
OvO_clf.fit(X,Y)

# Train OvR 
OvR_clf = OneVsRestClassifier(base_clf)
OvR_clf.fit(X,Y)

# Check
strlog = "OvO produces %d classifiers" %(len(OvO_clf.estimators_))
print(strlog)
strlog = "OvR produces %d classifiers" %(len(OvR_clf.estimators_))
print(strlog)


OvO produces 21 classifiers
OvR produces 7 classifiers


## Validation

In [ ]:
# Feature engineering, selection and rescaling to [0,1]
X_pred = scaler.transform(X_valid)
# PCA
X_pred = pca.transform(X_pred)
Y_true = Y_valid.values.ravel()

# predict
Y_pred_OvO = OvO_clf.predict(X_pred)
Y_pred_OvR = OvR_clf.predict(X_pred)


## Confusion Matrix

To check the performance of our model, we use Confusion Matrix as metric. This give us a general idea of how good is the model and let us compare it with the multiple combinations of feature that we have available.

In [ ]:
# Performance metrics

from sklearn.metrics import confusion_matrix, precision_recall_fscore_support

conf_mat_OvO = confusion_matrix(Y_true,Y_pred_OvO)
hits_OvO = np.trace(conf_mat_OvO)
conf_mat_OvR = confusion_matrix(Y_true,Y_pred_OvR)
hits_OvR = np.trace(conf_mat_OvR)

# Print out
print("\nOvO confusion matrix:\n")
print(conf_mat_OvO)
print("\n")
print( "OvO Hits  = %d"%(hits_OvO) ) 
print( "OvO Fails = %d"%(Y_true.shape[0]-hits_OvO) )
print( "OvO Accuracy = %f"%(hits_OvO/(Y_true.shape[0])))
print("\nOvR confusion matrix:\n")
print(conf_mat_OvR)
print( "\n")
print( "OvR Hits  = %d"%(hits_OvR) ) 
print( "OvR Fails = %d"%(Y_true.shape[0]-hits_OvR) )
print( "OvR Accuracy = %f"%(hits_OvR/Y_true.shape[0]))



OvO confusion matrix:

[[ 913 1345  817  455 1210 1487 2247]
 [1203 2159 1416  439 1117 1668 3330]
 [ 101   47  382   58  214  216  412]
 [   4   12   12    1   46   16   19]
 [  55   43   36    2   49   65  130]
 [  52   13  184   24   89   90  243]
 [  81   88  250   82   78   84  157]]


OvO Hits  = 3751
OvO Fails = 19490
OvO Accuracy = 0.161396

OvR confusion matrix:

[[ 613  950 1639  395 1210 2076 1591]
 [ 845  677 2853  294 1644 2902 2117]
 [ 198   71  119  124  266  437  215]
 [  17   21   12    7   16   32    5]
 [  34   66   35   11   46  103   85]
 [  84   17  143   36   50  265  100]
 [ 109   47  210  141   62  125  126]]


OvR Hits  = 1853
OvR Fails = 21388
OvR Accuracy = 0.079730


## Competition data

In [ ]:
# Load competition data
challenge_data = pd.read_csv('Reto 3-Dataset/reto3_testX.csv', header=0)
challenge_data = scaler.transform(challenge_data)
# PCA
challenge_features = pca.transform(challenge_data) # Principal components

# Inference
Y_chal_OvO = OvO_clf.predict(challenge_features)
Y_chal_OvR = OvR_clf.predict(challenge_features)

## Save results

In [ ]:
#np.savetxt('Reto3_Ypred.csv', Y_chal_OvO, fmt='%i', delimiter=',')