# Reto 3

## Miguel Ortiz y Andrea Castiella


In [1]:
import numpy  as np
import pandas as pd
import OurUtils as our
from sklearn.preprocessing import MinMaxScaler

In [2]:
# Read data
X_full = pd.read_csv('Reto 3-Dataset/reto3_trainX.csv', header=0, low_memory=False)
Y_full = pd.read_csv('Reto 3-Dataset/reto3_trainY.csv', header=0, low_memory=False)

print(X_full.head())
print(Y_full.head())

   altitud  azimut  inclinacion  DH_agua  DV_agua  DH_camino  sombra_9am  \
0     3351     354           19      450       95       1064         185   
1     2995      84            7      481       30       5154         231   
2     2884      72           25      210      -45        466         239   
3     3139      76           11      301       58       1368         234   
4     3018     312           17       30       10       1719         172   

   sombra_12pm  sombra_3pm  DH_fuego  ...  t31  t32  t33  t34  t35  t36  t37  \
0          203         153       711  ...    0    0    0    0    0    0    0   
1          227         129      5488  ...    0    0    0    0    0    0    0   
2          183          60      2123  ...    0    0    0    0    0    0    0   
3          220         117      3282  ...    0    0    1    0    0    0    0   
4          225         193      1961  ...    0    0    0    0    0    0    0   

   t38  t39  t40  
0    0    1    0  
1    0    0    0  
2    

## Split dataset
Train split: 80%

Validation split: 20%

In [3]:
# Split into train and validation
valid_size = 0.2
seed = 1234
X_train, Y_train, X_valid, Y_valid = \
   our.single_stratified_split(X_full, Y_full, test_size=valid_size, random_state=seed)

## Imbalanced class problem

In [ ]:
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler

over = SMOTE(random_state=seed, sampling_strategy={3:10000 , 4:10000 , 5: 10000, 6:10000 , 7:10000})
X_train, Y_train = over.fit_resample(X_train, Y_train)

under = RandomUnderSampler(random_state=seed, sampling_strategy={1:10000 , 2:10000})
X_train, Y_train = over.fit_resample(X_train, Y_train)

## Scale and transform features

In [4]:
scaler = MinMaxScaler()
X = scaler.fit_transform(X_train)
Y = Y_train.values.ravel() # Returns data as numpy array

from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=seed)
X, Y = sm.fit_resample(X, Y)

## PCA

In [6]:
# X_proy, pca = our.our_PCA(X)
# num_of_pc = len(pca.singular_values_)
# strTitle = '\n First %d principal components' %(num_of_pc)
# print(strTitle)
# print(pca.components_.T)
# strTitle = '\n First %d singular values ' %(num_of_pc)
# print(strTitle)
# print(pca.singular_values_.T)
# strTitle = '\n Explained Variance Ratio'
# print(strTitle)
# print(pca.explained_variance_ratio_.T)
# strTitle = '\n Accumulated Explained Variance Ratio'
# print(strTitle)
# print(np.cumsum(pca.explained_variance_ratio_.T))
# X = X_proy

(317296, 10)

 First 10 principal components
[[-2.42711647e-01  1.26445975e-01  5.13225464e-02 -6.60406887e-02
   2.62259679e-01 -1.95525696e-01 -1.18671165e-02  1.63211750e-01
   2.63858331e-02  7.25965647e-02]
 [ 7.57239214e-03 -1.03929194e-01  5.99024743e-01 -5.28692340e-01
  -6.39832101e-02  1.46704814e-01  3.31509814e-01  4.05015071e-03
  -8.40157146e-02  6.42404442e-02]
 [ 6.46370411e-02 -4.10950106e-02 -1.44687325e-02  1.06456960e-01
  -2.91531920e-02  5.35449359e-02  2.52837527e-01  1.28762734e-01
  -4.25619117e-02  1.35293204e-01]
 [-7.14186410e-02  1.21396225e-03  1.80844329e-02 -4.84997933e-02
   1.08364549e-01 -1.73484305e-01  2.64186959e-02  1.56670917e-01
  -1.34270266e-01  3.70316235e-02]
 [-3.98038250e-03 -1.54001386e-02 -8.64570694e-04 -8.37655440e-03
   3.71384247e-02 -5.67367681e-02  6.17587103e-02  8.35818089e-02
  -7.17014597e-02  5.98763573e-02]
 [-1.24368793e-01  1.25360173e-01  9.17883483e-02 -8.09848985e-02
   3.54391021e-02 -2.05471828e-01  5.82251738e-03  2.5

## Multiclass. OvO vs OvR

In [12]:
# Multiclass
from sklearn.multiclass import OneVsOneClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.mixture import GaussianMixture
'''
N_components = 3    #<-- number of Gaussian components
cov_type = 'full'   #<-- choices are:  ‘full’ , ‘tied’ , ‘diag’ , ‘spherical’
init_params='random'#<-- every time begins at a different point
max_iter=1000       #<-- number of iterations before stop (if not convergence)

gmm_1 = GaussianMixture(n_components=N_components, \
                        covariance_type=cov_type, init_params=init_params, max_iter=max_iter)
gmm_2 = GaussianMixture(n_components=N_components, \
                        covariance_type=cov_type, init_params=init_params, max_iter=max_iter)
gmm_3 = GaussianMixture(n_components=N_components, \
                        covariance_type=cov_type, init_params=init_params, max_iter=max_iter)
gmm_4 = GaussianMixture(n_components=N_components, \
                        covariance_type=cov_type, init_params=init_params, max_iter=max_iter)
gmm_5 = GaussianMixture(n_components=N_components, \
                        covariance_type=cov_type, init_params=init_params, max_iter=max_iter)
gmm_6 = GaussianMixture(n_components=N_components, \
                        covariance_type=cov_type, init_params=init_params, max_iter=max_iter)
gmm_7 = GaussianMixture(n_components=N_components, \
                        covariance_type=cov_type, init_params=init_params, max_iter=max_iter)

X = X_proy
# Train OvO
ind = np.where(Y==1)
X_1 = X[ind]
Y_1 = Y[ind]
print(ind[0].shape)
gmm_1.fit(X_1, Y_1)

ind = np.where(Y==2)
X_2 = X[ind]
Y_2 = Y[ind]
print(ind[0].shape)
gmm_2.fit(X_2, Y_2)

ind = np.where(Y==3)
X_3 = X[ind]
Y_3 = Y[ind]
print(ind[0].shape)
gmm_3.fit(X_3, Y_3)

ind = np.where(Y==4)
X_4 = X[ind]
Y_4 = Y[ind]
print(ind[0].shape)
gmm_4.fit(X_4, Y_4)

ind = np.where(Y==5)
X_5 = X[ind]
Y_5 = Y[ind]
print(ind[0].shape)
gmm_5.fit(X_5, Y_5)

ind = np.where(Y==6)
X_6 = X[ind]
Y_6 = Y[ind]
print(ind[0].shape)
gmm_6.fit(X_6, Y_6)

ind = np.where(Y==7)
X_7 = X[ind]
Y_7 = Y[ind]
print(ind[0].shape)
gmm_7.fit(X_7, Y_7)
'''

classifier = GaussianMixture(n_components = 7 ,covariance_type='diag',max_iter=100,random_state = 42,tol=0.1,n_init = 1)
means = np.array([X[Y == i].mean(axis=0) 
                                for i in range(1,8)]) 
print(means.shape)
classifier.means_init = np.array([X[Y == i].mean(axis=0) 
                                for i in range(1,8)]) 
classifier.fit(X)


(7, 54)


GaussianMixture(covariance_type='diag',
                means_init=array([[6.34711767e-01, 4.32562470e-01, 2.12072153e-01, 1.94681638e-01,
        2.64124454e-01, 3.66540639e-01, 8.35169777e-01, 8.53266758e-01,
        5.65369109e-01, 2.80584682e-01, 4.98588069e-01, 8.66351924e-02,
        4.14776738e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 8.38333922e-04, 0.00000000e+00, 0.00000...
        0.00000000e+00, 0.00000000e+00, 3.45429247e-04, 7.19202259e-03,
        2.89445817e-02, 1.04571126e-02, 0.00000000e+00, 0.00000000e+00,
        1.40602560e-03, 0.00000000e+00, 4.58877515e-02, 6.90522414e-03,
        1.21337804e-02, 4.26065506e-02, 3.22181479e-02, 3.46364278e-03,
        3.83492373e-02, 3.92693258e-03, 1.38545711e-02, 2.95812094e-01,
        2.72899753e-01, 1.79615011e-01]]),
                n_components=7, random_state=42, tol=0.1)

## Validation

In [16]:
'''# Feature engineering, selection and rescaling to [0,1]
X_pred = scaler.transform(X_valid)
# PCA
X_pred = pca.transform(X_pred)
Y_true = Y_valid.values.ravel()

# predict

y_score1 = np.exp(gmm_1.score_samples(X_pred))
y_score2 = np.exp(gmm_2.score_samples(X_pred))
y_score3 = np.exp(gmm_3.score_samples(X_pred))
y_score4 = np.exp(gmm_4.score_samples(X_pred))
y_score5 = np.exp(gmm_5.score_samples(X_pred))
y_score6 = np.exp(gmm_6.score_samples(X_pred))
y_score7 = np.exp(gmm_7.score_samples(X_pred))

y_scores = np.vstack([y_score1, y_score2, y_score3, y_score4, y_score5, y_score6, y_score7])
print(y_scores.shape)
y_hat = np.where(y_scores==np.max(y_scores, axis=0))
y_hat = y_hat[0] + 1
# print(y_hat[10000:100010], y_hat.shape)
# print("=====")
# print(y_score1[0], y_score1.shape)
# print(y_score2[0], y_score2.shape)
# print(y_score3[0], y_score3.shape)
# print(y_score4[0], y_score4.shape)
# print(y_score5[0], y_score5.shape)
# print(y_score6[0], y_score6.shape)
# print(y_score7[0], y_score7.shape)

'''
Y_true = Y_valid.values.ravel()
X_pred = classifier.predict(X_valid)
train_accuracy = np.mean(X_pred.ravel() == Y_true)*100
print('train accuracy:',train_accuracy)



train accuracy: 19.762488705305277


## Confusion Matrix

To check the performance of our model, we use Confusion Matrix as metric. This give us a general idea of how good is the model and let us compare it with the multiple combinations of feature that we have available.

In [17]:
# Performance metrics

from sklearn.metrics import confusion_matrix, precision_recall_fscore_support

conf_mat = confusion_matrix(Y_true, X_pred)
hits = np.trace(conf_mat)

# Print out
print("\nConfusion matrix:\n")
print(conf_mat)
print("\n")
print( "OvO Hits  = %d"%(hits) ) 
print( "OvO Fails = %d"%(Y_true.shape[0]-hits) )
print( "OvO Accuracy = %f"%(hits/(Y_true.shape[0])))



Confusion matrix:

[[3959    0    0    0    0 4515    0]
 [5074    0    0    0    0 6258    0]
 [  72    0    0    0    0 1358    0]
 [   0    0    0    0    0  110    0]
 [  50    0    0    0    0  330    0]
 [  61    0    0    0    0  634    0]
 [ 346    0    0    0    0  474    0]]


OvO Hits  = 4593
OvO Fails = 18648
OvO Accuracy = 0.197625
